# Generated by Django 6.0.4 on 2026-04-09 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterBranch',
            fields=[
                ('shelter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='KennelCage',
            fields=[
                ('kennel_id', models.AutoField(primary_key=True, serialize=False)),
                ('kennel_code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Indoor', 'Indoor'), ('Outdoor', 'Outdoor'), ('Quarantine', 'Quarantine')], max_length=20)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=20)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kennels', to='shelter.shelterbranch')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeRecord',
            fields=[
                ('intake_id', models.AutoField(primary_key=True, serialize=False)),
                ('intake_type', models.CharField(choices=[('Stray', 'Stray'), ('Owner Surrender', 'Owner Surrender'), ('Transfer', 'Transfer'), ('Rescue', 'Rescue')], max_length=50)),
                ('intake_date', models.DateField(auto_now_add=True)),
                ('condition_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_records', to='animals.pet')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.shelterbranch')),
            ],
        ),
    ]
