# Generated by Django 6.0.4 on 2026-04-09 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FosterAssignment',
            fields=[
                ('foster_id', models.AutoField(primary_key=True, serialize=False)),
                ('foster_name', models.CharField(max_length=200)),
                ('foster_phone', models.CharField(max_length=20)),
                ('foster_address', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_assignments', to='animals.pet')),
            ],
        ),
    ]
