# Generated by Django 6.0.4 on 2026-04-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0002_pet_photo_alter_pet_age_alter_pet_species_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foster',
            fields=[
                ('foster_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('experience_years', models.IntegerField(default=0, help_text='Years of pet fostering experience')),
                ('preferred_species', models.CharField(blank=True, help_text='Preferred animal species', max_length=100)),
                ('max_pets', models.IntegerField(default=1, help_text='Maximum number of pets they can foster')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FosterApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('interview_schedule', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('foster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='fostering.foster')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FosterAssignment',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('foster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='fostering.foster')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_assignments', to='animals.pet')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FosterCheckIn',
            fields=[
                ('checkin_id', models.AutoField(primary_key=True, serialize=False)),
                ('checkin_date', models.DateField()),
                ('pet_condition', models.TextField()),
                ('foster_feedback', models.TextField(blank=True)),
                ('issues', models.TextField(blank=True)),
                ('next_checkin_date', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='fostering.fosterassignment')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
