# Generated by Django 6.0.4 on 2026-04-09 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('adopter_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('has_other_pets', models.BooleanField(default=False)),
                ('has_children', models.BooleanField(default=False)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'adopters',
            },
        ),
        migrations.CreateModel(
            name='AdoptionApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('interview_schedule', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='adoptions.adopter')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='animals.pet')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adoption_applications',
            },
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('adoption_id', models.AutoField(primary_key=True, serialize=False)),
                ('adoption_date', models.DateField()),
                ('adoption_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='adoptions.adopter')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoptions', to='animals.pet')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='adoption', to='adoptions.adoptionapplication')),
            ],
            options={
                'db_table': 'adoptions',
            },
        ),
        migrations.CreateModel(
            name='HomeVisit',
            fields=[
                ('visit_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_visits', to='adoptions.adoptionapplication')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'home_visits',
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_datetime', models.DateTimeField()),
                ('result', models.CharField(blank=True, choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='adoptions.adoptionapplication')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interviews',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Card', 'Card')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('reference_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=20)),
                ('adoption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='adoptions.adoption')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
