# Generated by Django 6.0.4 on 2026-04-09 19:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('pet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], max_length=50)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.IntegerField(help_text='Age in months', validators=[django.core.validators.MinValueValidator(0)])),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('vaccination_status', models.BooleanField(default=False)),
                ('spay_neuter_status', models.BooleanField(default=False)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('intake_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted')], default='Available', max_length=20)),
            ],
            options={
                'db_table': 'pets',
            },
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('vet_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('clinic_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('license_no', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'veterinary',
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('vaccination_id', models.AutoField(primary_key=True, serialize=False)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose_no', models.IntegerField()),
                ('vaccination_date', models.DateField()),
                ('next_due_date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='animals.pet')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.veterinary')),
            ],
            options={
                'db_table': 'vaccinations',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('medical_id', models.AutoField(primary_key=True, serialize=False)),
                ('visit_date', models.DateField()),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='animals.pet')),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.veterinary')),
            ],
            options={
                'db_table': 'medical_records',
            },
        ),
    ]
