# Generated by Django 6.0.4 on 2026-05-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='quarantine_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='quarantine_location',
            field=models.CharField(blank=True, help_text="e.g., 'Kennel B-12', 'Isolation Ward'", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='quarantine_reason',
            field=models.TextField(blank=True, help_text="e.g., 'Exposed to kennel cough', 'Bite quarantine'", null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='quarantine_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Adopted', 'Adopted'), ('Quarantine', 'Quarantine'), ('Medical', 'Medical'), ('Fostered', 'Fostered')], default='Available', max_length=20),
        ),
    ]
