# Generated by Django 6.0.4 on 2026-04-09 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(help_text='Age in months', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Rabbit', 'Rabbit'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Pending', 'Pending'), ('Adopted', 'Adopted'), ('Fostered', 'Fostered'), ('Medical', 'Medical'), ('Quarantine', 'Quarantine')], default='Available', max_length=20),
        ),
    ]
