# Generated by Django 6.0.4 on 2026-05-14 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_pet_quarantine_end_date_pet_quarantine_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-visit_date']},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-intake_date']},
        ),
        migrations.AlterModelOptions(
            name='vaccination',
            options={'ordering': ['-vaccination_date']},
        ),
        migrations.AddField(
            model_name='pet',
            name='birth_date',
            field=models.DateField(blank=True, help_text='Use either birth_date OR age', null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AddField(
            model_name='pet',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='is_accredited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in months (if birth_date not provided)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='quarantine_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='quarantine_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
