# Generated by Django 6.0.4 on 2026-05-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_pet_created_at_pet_created_by_pet_created_by_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinary',
            name='action',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='veterinary',
            name='voucher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
